package com.example.employeeapp.controller;
import com.example.employeeapp.entity.*; import com.example.employeeapp.repository.*; import com.example.employeeapp.exception.ApiException; import jakarta.validation.Valid; import org.springframework.http.*;
import org.springframework.web.multipart.MultipartFile; import org.springframework.web.bind.annotation.*; import java.time.*; import java.time.format.DateTimeFormatter; import java.util.*;
@RestController @RequestMapping("/api/applications") @CrossOrigin(origins="*") public class ApplicationController {
 private final CandidateApplicationRepository repo; private final ProjectRepository projects; public ApplicationController(CandidateApplicationRepository r,ProjectRepository p){repo=r;projects=p;}
 @GetMapping public List<CandidateApplication> all(){return repo.findAll(org.springframework.data.domain.Sort.by(org.springframework.data.domain.Sort.Direction.DESC,"appliedAt"));}
 @GetMapping("/candidate/{email}") public List<CandidateApplication> byCandidate(@PathVariable String email){return repo.findByEmailIgnoreCaseOrderByAppliedAtDesc(email);}
 @GetMapping("/candidate/username/{username}") public List<CandidateApplication> byCandidateUsername(@PathVariable String username){return repo.findByCandidateUsernameIgnoreCaseOrderByAppliedAtDesc(username);}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) public CandidateApplication apply(@Valid @RequestBody CandidateApplication a){ if(a.getProjectId()==null) throw new ApiException("Please select a job/project"); Project p=projects.findById(a.getProjectId()).orElseThrow(()->new ApiException("Job not found")); if(!skillsMatch(a.getSkills(), p.getSkills())) throw new ApiException("Your skills do not match the required skills for this job. Required: " + p.getSkills()); boolean activeApplication = repo.findByCandidateUsernameIgnoreCaseOrderByAppliedAtDesc(a.getCandidateUsername()).stream()
   .anyMatch(existing -> Objects.equals(existing.getProjectId(), a.getProjectId())
     && existing.getStatus() != CandidateApplication.Status.MANAGER_REJECTED
     && existing.getStatus() != CandidateApplication.Status.ADMIN_REJECTED);
 if(activeApplication) throw new ApiException("You already have an active application for this job"); a.setCandidateName(a.getCandidateName().trim()); a.setCandidateUsername(a.getCandidateUsername().trim()); a.setEmail(a.getEmail().trim()); a.setPhone(a.getPhone().trim()); a.setSkills(a.getSkills().trim()); a.setAppliedRole(a.getAppliedRole().trim()); a.setComment(a.getComment()==null?"":a.getComment().trim()); a.setProjectName(p.getName()); a.setApplicationCode(nextCode(a)); a.setStatus(CandidateApplication.Status.PENDING); a.setRejectionComment(null); return repo.saveAndFlush(a);}
 private String nextCode(CandidateApplication a){
  String raw = a.getCandidateName()==null ? "CAN" : a.getCandidateName().trim().replaceAll("[^A-Za-z]", "");
  String prefix = raw.length() >= 3 ? raw.substring(0,3) : (raw + "CAN").substring(0,3);
  String x = prefix + "-";
  int max = repo.findAll().stream()
    .map(CandidateApplication::getApplicationCode)
    .filter(Objects::nonNull)
    .filter(v -> v.regionMatches(true,0,x,0,x.length()))
    .map(v -> v.substring(x.length()))
    .filter(v -> v.matches("\\d+"))
    .mapToInt(Integer::parseInt).max().orElse(100);
  return prefix + "-" + (max + 1);
}
 @PutMapping("/{id}/manager") public CandidateApplication manager(@PathVariable Long id,@RequestBody Decision r){CandidateApplication a=find(id); if(a.getStatus()!=CandidateApplication.Status.PENDING)throw new ApiException("Manager can review only newly applied candidates"); String s=up(r.status()); if("MANAGER_APPROVED_REVIEW".equals(s))a.setStatus(CandidateApplication.Status.MANAGER_APPROVED_REVIEW); else if("MANAGER_REJECTED".equals(s)){need(r);a.setStatus(CandidateApplication.Status.MANAGER_REJECTED);a.setRejectionComment(r.comment().trim());} else throw new ApiException("Manager can choose Approved - Review or Reject"); return repo.saveAndFlush(a);}
 @PutMapping("/{id}/admin") public CandidateApplication admin(@PathVariable Long id,@RequestBody Decision r){CandidateApplication a=find(id); String s=up(r.status()); if("ADMIN_L1_REVIEW".equals(s)){if(a.getStatus()!=CandidateApplication.Status.MANAGER_APPROVED_REVIEW)throw new ApiException("Admin can start L1 only after Manager approval"); a.setStatus(CandidateApplication.Status.ADMIN_L1_REVIEW);} else if("ADMIN_REJECTED".equals(s)){if(a.getStatus()!=CandidateApplication.Status.MANAGER_APPROVED_REVIEW && a.getStatus()!=CandidateApplication.Status.ADMIN_L1_REVIEW && a.getStatus()!=CandidateApplication.Status.L1_COMPLETED_MANAGER_APPROVED)throw new ApiException("Admin can reject only applications currently in Admin review"); need(r); a.setStatus(CandidateApplication.Status.ADMIN_REJECTED); a.setRejectionComment(r.comment().trim());} else throw new ApiException("Admin can choose L1 Interview Review or Reject"); return repo.saveAndFlush(a);}
 @PutMapping("/{id}/manager/comment") public CandidateApplication managerComment(@PathVariable Long id,@RequestBody Decision r){CandidateApplication a=find(id); if(a.getStatus()!=CandidateApplication.Status.ADMIN_REJECTED)throw new ApiException("Manager comments can be added only to Admin Rejected applications"); a.setManagerComment(r.comment()==null?"":r.comment().trim()); return repo.saveAndFlush(a);} @PutMapping("/{id}/manager/l1-complete") public CandidateApplication l1(@PathVariable Long id){CandidateApplication a=find(id);if(a.getStatus()!=CandidateApplication.Status.ADMIN_L1_REVIEW)throw new ApiException("Admin must start L1 Interview Review first");a.setStatus(CandidateApplication.Status.L1_COMPLETED_MANAGER_APPROVED);return repo.saveAndFlush(a);}
 @PutMapping("/{id}/admin/final-approve") public CandidateApplication finalApprove(@PathVariable Long id){CandidateApplication a=find(id);if(a.getStatus()!=CandidateApplication.Status.L1_COMPLETED_MANAGER_APPROVED)throw new ApiException("Manager must complete L1 and approve first");a.setStatus(CandidateApplication.Status.SELECTED);return repo.saveAndFlush(a);}

 @PostMapping(value="/{id}/resume", consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public CandidateApplication uploadResume(@PathVariable Long id,@RequestParam("resume") MultipartFile file) { CandidateApplication a=find(id); if(file==null || file.isEmpty()) throw new ApiException("Please select a resume file"); String name=file.getOriginalFilename()==null?"resume":file.getOriginalFilename(); String lower=name.toLowerCase(Locale.ROOT); boolean allowed=lower.endsWith(".pdf")||lower.endsWith(".doc")||lower.endsWith(".docx"); if(!allowed) throw new ApiException("Resume must be a PDF, DOC or DOCX file"); if(file.getSize()>10*1024*1024) throw new ApiException("Resume must be 10 MB or smaller"); try { a.setResumeData(file.getBytes()); a.setResumeFileName(name); a.setResumeContentType(file.getContentType()); return repo.saveAndFlush(a); } catch(Exception e){ throw new ApiException("Unable to save resume"); } }
 @GetMapping("/{id}/resume") public ResponseEntity<byte[]> downloadResume(@PathVariable Long id) { CandidateApplication a=find(id); if(a.getResumeData()==null) throw new ApiException("Resume not uploaded"); MediaType type; try { type=MediaType.parseMediaType(a.getResumeContentType()==null?MediaType.APPLICATION_OCTET_STREAM_VALUE:a.getResumeContentType()); } catch(Exception e){ type=MediaType.APPLICATION_OCTET_STREAM; } return ResponseEntity.ok().contentType(type).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+a.getResumeFileName()+"\"").body(a.getResumeData()); }
 private boolean skillsMatch(String candidate,String required){ if(required==null||required.isBlank()) return true; if(candidate==null||candidate.isBlank()) return false; Set<String> c=skillTokens(candidate); Set<String> r=skillTokens(required); return r.stream().anyMatch(c::contains); }
 private Set<String> skillTokens(String s){ return Arrays.stream(s.toLowerCase(Locale.ROOT).split("[,;|]")).map(String::trim).filter(v->!v.isBlank()).collect(java.util.stream.Collectors.toSet()); }
 private CandidateApplication find(Long id){return repo.findById(id).orElseThrow(()->new ApiException("Application not found"));} private String up(String s){return s==null?"":s.toUpperCase();} private void need(Decision r){if(r.comment()==null||r.comment().isBlank())throw new ApiException("Rejection comment is required");} public record Decision(String status,String comment){}
}
